import React, { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import Navbar from '../navbar/Navbar.jsx';
import { FaDownload, FaSpinner } from 'react-icons/fa';
import axios from 'axios';
import jsPDF from 'jspdf';
import { useRef } from 'react';

const BookingDetails = () => {
    const [search, setSearchDetails] = useState(null);
    const [user, setUserDetails] = useState(null);
    const [hotel, setHotelDetails] = useState(null);
    const [room, setRoomDetails] = useState(null);
    const { hotelId, roomId } = useParams();
    const [noofdays, setNoofdays] = useState(0);
    const [loading, setLoading] = useState(false);
    const API_URL = 'https://bookify-v2-2.onrender.com';
    
const invoiceRef = useRef(null);

    useEffect(() => {
        const fetchSearchDetails = () => {
            const savedSearchDetails = localStorage.getItem('searchState');
            if (savedSearchDetails) {
                const parsedDetails = JSON.parse(savedSearchDetails);
                setSearchDetails(parsedDetails);
                const startDate = new Date(parsedDetails.date[0]?.startDate);
                const endDate = new Date(parsedDetails.date[0]?.endDate);
                const days = (endDate - startDate) / (1000 * 3600 * 24);
                setNoofdays(days);
            }
        };

        const fetchUserDetails = async () => {
            try {
                const response = await axios.get(`${API_URL}/api/auth/profile`, {
                    headers: {
                        Authorization: ` ${localStorage.getItem('token')}`,
                    },
                });
                setUserDetails(response.data);
            } catch (error) {
                console.error("Error fetching user details:", error);
            }
        };

        const fetchHotelDetails = async () => {
            try {
                const response = await axios.get(`${API_URL}/api/hotels/${hotelId}`, { withCredentials: true });
                setHotelDetails(response.data);
            } catch (error) {
                console.error("Error fetching hotel details:", error);
            }
        };

        const fetchRoomDetails = async () => {
            try {
                const response = await axios.get(`${API_URL}/api/rooms/${roomId}`, { withCredentials: true });
                setRoomDetails(response.data);
            } catch (error) {
                console.error("Error fetching room details:", error);
            }
        };

        fetchSearchDetails();
        fetchUserDetails();
        fetchHotelDetails();
        fetchRoomDetails();
    }, [hotelId, roomId]);

    const generatePDF = () => {
        const doc = new jsPDF();
        doc.setFontSize(16);
        doc.text('Hotel Booking Invoice', 20, 20);
        doc.setFontSize(12);

        doc.text(`Hotel Name: ${hotel.name}`, 20, 40);
        doc.text(`Address: ${hotel.address}`, 20, 50);
        doc.text(`City: ${hotel.city}`, 20, 60);
        doc.text(`Check-in Date: ${new Date(search.date[0]?.startDate).toLocaleDateString()}`, 20, 70);
        doc.text(`Check-out Date: ${new Date(search.date[0]?.endDate).toLocaleDateString()}`, 20, 80);
        doc.text(`Invoice Number: ${search.invoiceNumber}`, 20, 90);

        doc.text(`Name: ${user.username}`, 20, 110);
        doc.text(`Email: ${user.email}`, 20, 120);
        doc.text(`Phone: ${user.phone}`, 20, 130);
        doc.text(`Room Type: ${room.title}`, 20, 150);
        doc.text(`No of Days: ${noofdays}`, 20, 160);
        doc.text(`Total Amount: $${room.room_price * noofdays}`, 20, 170);

        doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text('Invoice generated by BookifyV2', 20, 280);
        return doc;
    };

    const handleDownloadReceipt = async () => {
        setLoading(true);
        const doc = generatePDF();
        const pdfBlob = doc.output('blob');

        try {
            const response = await axios.post(`${API_URL}/api/generate`, {
                guestName: user.username,
                checkIn: new Date(search.date[0]?.startDate).toLocaleDateString(),
                checkOut: new Date(search.date[0]?.endDate).toLocaleDateString(),
                roomType: room.title,
                totalAmount: room.room_price * noofdays,
                email: user.email
            }, {
                headers: {
                    Authorization: ` ${localStorage.getItem('token')}`,
                },
            });

            const { preSignedUrl } = response.data;

            await axios.put(preSignedUrl, pdfBlob, {
                headers: {
                    'Content-Type': 'application/pdf',
                },
            });

            doc.save(`invoice_${search.invoiceNumber}.pdf`);
        } catch (error) {
            console.error("Error generating and uploading bill:", error);
        } finally {
            setLoading(false);
        }
    };

    if (!search || !user || !hotel || !room) {
        return (
            <div className="min-h-screen bg-gray-100 flex items-center justify-center">
                <p className="text-xl text-gray-500">Loading booking details...</p>
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-gradient-to-br from-black  via-purple-950 to-black text-gray-200">
            {/* Floating Navbar */}
            <div className="fixed top-0 left-0 w-full z-50 bg-gray-950/80 backdrop-blur border-b border-gray-700">
                <Navbar />
            </div>

            {/* Main Invoice Section */}
            <div className="pt-24 px-4 pb-10">
            <div ref={invoiceRef} className="max-w-3xl mx-auto bg-gray-900/60 backdrop-blur-lg shadow-2xl rounded-2xl p-10 border border-gray-700">
                    <h1 className="text-4xl font-bold text-center text-indigo-400 mb-10 tracking-wide">
                        🧾 Hotel Booking Invoice
                    </h1>

                    {/* Hotel Info */}
                    <section className="mb-8">
                        <h2 className="text-lg font-semibold text-indigo-300 mb-4">🏨 Hotel Information</h2>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-gray-300">
                            <p><span className="font-semibold">Name:</span> {hotel.name}</p>
                            <p><span className="font-semibold">City:</span> {hotel.city}</p>
                            <p><span className="font-semibold">Address:</span> {hotel.address}</p>
                            <p><span className="font-semibold">Invoice #:</span> {search.invoiceNumber}</p>
                            <p><span className="font-semibold">Check-in:</span> {new Date(search.date[0]?.startDate).toLocaleDateString()}</p>
                            <p><span className="font-semibold">Check-out:</span> {new Date(search.date[0]?.endDate).toLocaleDateString()}</p>
                        </div>
                    </section>

                    {/* User Info */}
                    <section className="mb-8 border-t border-gray-700 pt-6">
                        <h2 className="text-lg font-semibold text-indigo-300 mb-4">👤 Billed To</h2>
                        <div className="space-y-2">
                            <p><span className="font-semibold">Name:</span> {user.username}</p>
                            <p><span className="font-semibold">Email:</span> {user.email}</p>
                            <p><span className="font-semibold">Phone:</span> {user.phone}</p>
                        </div>
                    </section>

                    {/* Room Info */}
                    <section className="mb-8 border-t border-gray-700 pt-6">
                        <h2 className="text-lg font-semibold text-indigo-300 mb-4">🛏️ Room Details</h2>
                        <div className="overflow-x-auto">
                            <table className="w-full text-sm">
                                <thead>
                                    <tr className="text-left border-b border-gray-700 text-gray-400">
                                        <th className="py-2">Room Type</th>
                                        <th className="py-2">Days</th>
                                        <th className="py-2">Rate</th>
                                        <th className="py-2 text-right">Total</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr className="border-b border-gray-700 text-gray-200">
                                        <td className="py-3">{room.title}</td>
                                        <td className="py-3">{noofdays}</td>
                                        <td className="py-3">${room.room_price}</td>
                                        <td className="py-3 text-right font-semibold">${room.room_price * noofdays}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </section>

                    <div className="mt-8 text-center text-sm text-gray-400 pt-4">
                        <p>
                            Invoice generated by <span className="text-indigo-400 font-semibold">BookifyV2</span>
                        </p>
                    </div>

                    {/* Download Button */}
                    <div className="mt-10 flex justify-center">
                        <button
                            onClick={handleDownloadReceipt}
                            disabled={loading}
                            className={`flex items-center gap-2 px-6 py-3 rounded-lg font-medium text-white shadow-md transition duration-200 ${loading ? 'bg-gray-600 cursor-not-allowed' : 'bg-indigo-600 hover:bg-indigo-700'
                                }`}
                        >
                            {loading ? (
                                <>
                                    <FaSpinner className="animate-spin" />
                                    Generating...
                                </>
                            ) : (
                                <>
                                    <FaDownload />
                                    Download Invoice
                                </>
                            )}
                        </button>
                    </div>
                </div>
            </div>
        </div>

    );
};

export default BookingDetails;
